-- 코드를 작성해주세요
-- 코드를 작성해주세요
SELECT CE.ID
FROM ECOLI_DATA CE
LEFT JOIN ECOLI_DATA PE
ON CE.PARENT_ID = PE.ID
LEFT JOIN ECOLI_DATA PPE
ON PE.PARENT_ID = PPE.ID
LEFT JOIN ECOLI_DATA PPPE
ON PPE.PARENT_ID = PPPE.ID
WHERE PPE.ID IS NOT NULL
AND PPPE.ID IS NULL
ORDER BY CE.ID
# 1 -> 3 -> 7
# 2 -> 4 -> 6 -> 8
# 2 -> 5