-- 코드를 작성해주세요
SELECT CE.ID, CE.GENOTYPE, PE.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA CE
LEFT JOIN ECOLI_DATA PE
ON CE.PARENT_ID = PE.ID
WHERE CE.PARENT_ID IS NOT NULL
AND CE.GENOTYPE & PE.GENOTYPE = PE.GENOTYPE
ORDER BY ID

