# todo : 다시풀기
# 바깥 WHERE 에 한번더 DATE를 걸지 않았다
# -- 코드를 입력하세요
SELECT CAST(DATE_FORMAT(START_DATE, '%m') AS UNSIGNED) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08' AND DATE_FORMAT(START_DATE, '%Y-%m') < '2022-11'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5 
) AND DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08' AND DATE_FORMAT(START_DATE, '%Y-%m') < '2022-11'
GROUP BY MONTH, CAR_ID
# HAVING COUNT(*) >= 1
ORDER BY MONTH ASC, CAR_ID DESC